let links = `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<url>
<loc>https://www.midtown-bbq.com/ja/home</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/concept</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/menu</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/orders</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/menu/delivery</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/menu/party</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/menu/lunch</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/taplist/nagoya</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/taplist/yokohama</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/menu/takeout</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/reservations</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/reservations/sent</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/nagoya</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/nagoya/eventsxxx</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/yokohama</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/shop/giftcards</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/ja/shop/sauces</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/conceito</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/menu</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/orders</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/menu/delivery</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/menu/festas</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/menu/almoco</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/taplist/nagoya</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/taplist/yokohama</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/menu/takeout</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/reservas</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/reservations/sent</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/nagoya</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/nagoya/events</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/yokohama</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/shop/giftcards</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/pt-br/shop/sauces</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/concept</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/menu</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/menu/delivery</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/menu/party</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/menu/lunch</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/taplist/nagoya</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/taplist/yokohama</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/reservations</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/nagoya</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/yokohama</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/shop/giftcards</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/shop/sauces</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/salads-&-starters-c48541472</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/barbecue-c48538374</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/burgers-c48543440</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/steaks-c48541473</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/drinks-c59362029</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/craft-beers-c59369028</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/soft-drinks-c59369027</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/desserts-c59366097</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/general-store-c59369097</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/blitzen-belgian-tripel-p286944717</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/battleship-double-ipa-p286997550</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/Robb’s-Original-Hot-Sauce-p233194060</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/Midtown-BBQ-Barbecue-Sauce-p233194058</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/chocolate-brownie-p233177057</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/apple-pie-p233193052</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/lemon-tart-p233194017</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/oreo-cheesecake-p233193049</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/chocolate-cheesecake-p233177038</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/caramel-cheesecake-p233177037</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/berry-cheesecake-p233173013</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/pilsner-p233077830</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/signature-pale-ale-p233077829</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/nitro-stout-p233077819</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/fanta-grape-p232990603</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/fanta-orange-p232990601</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/sprite-(lemon-lime)-p233073004</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/diet-ginger-ale-p233073002</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/ginger-ale-p232990597</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/diet-dr-pepper-p232990586</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/north-by-northwest-ipa-p232999479</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/kolsch-p232979493</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/flagship-ipa-p232990545</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/hazy-pale-ale-p232999478</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/heroica-red-ale-p232814654</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/black-angel-ipa-p232814631</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/dr-pepper-p232636946</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/coke-zero-p232636945</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/coca-cola-p232632668</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/300g-(11oz)-A5-wagyu-tenderloin-steak-2-sides-p232636806</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/dinosaur-tray-3-double-sides-p232632429</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/the-melting-fondue-cheeseburger-1-side-p232632294</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/bbq-buffalo-chicken-cheddar-burger-1-side-p232636379</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/chicken-bacon-ranch-cheddar-burger-1-side-p232636371</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/pulled-pork-sandwich-1-side-p232632273</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/the-great-outdoors-1-side-p232636349</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/little-pig-1-side-p232632256</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/gorgonzola-cheese-burger-1-side-p232636297</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/spicy-jalapeno-cheeseburger-1-side-p232632234</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/bbq-bacon-cheeseburger-1-side-p232636252</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/double-cheeseburger-1-side-p232523925</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/fries-&-dip-p231512771</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/caesar-salad-p231401954</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/garden-salad-p231408000</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/loaded-nachos-p231401936</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/300g-(11oz)-filet-mignon-steak-2-sides-p193108226</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/fresh-salsa-&-chips-p193108216</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/smoked-sausage-p193108211</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/spicy-chicken-bites-p193108210</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/A5-black-wagyu-brisket-2-sides-p193099195</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/barbecue-chicken-(boneless)-2-sides-p193106239</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/bbq-chicken-&-ribs-2-sides-p192813203</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/signature-bbq-plate-2-sides-p192813198</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/angus-ribeye-steak-2-sides-p189683178</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/big-boy-tray-3-sides-p189683174</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/tacos-p189682174</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/classic-cheeseburger-1-side-p189596178</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
<url>
<loc>https://www.midtown-bbq.com/orders/smoked-spareribs-2-sides-p189507506</loc>
<priority>1.0</priority>
<changefreq>monthly</changefreq>
<lastmod>2021-07-12</lastmod>
</url>
</urlset>`;
// let matches = links.match(/(https\:\/\/www\.midtown\-bbq\.com\/orders\/)[0-9a-zA-Z\&\-]*/g);
let matches = links.match(/(https\:\/\/www\.midtown\-bbq\.com\/orders\/)+.*(?=\<)/g);
console.log(matches);